[package]
name = "snmptrap-forwarder"
version = "0.0.1"
authors = ["Lương Quang Mạnh <luongquangmanh85@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { git = "https://github.com/clap-rs/clap" }
reqwest = { version = "0.10.3", features = ["json"] }
tokio = { version = "0.2.13", features = ["full"] }

[[bin]]
name = "snmptrap-forwarder"
path = "src/main.rs"
